spring:
  application:
    name: gateway-service
#Routes
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**, /module/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
              - Path=/auth/**
server:
  port: 3000

#Registry Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/