spring:
  application:
    name: gateway-service
  #Routes
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**, /module/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
              - Path=/auth/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
          filters:
            - AuthFilter
        - id: parameter-service
          uri: lb://parameter-service
          predicates:
            - Path=/parameter/**
          filters:
            - AuthFilter
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/customer/**
          filters:
            - AuthFilter
server:
  port: 3010

#Registry Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://198.211.113.192:3001/eureka/